# Generated by Django 2.0.1 on 2018-06-12 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=32)),
                ('full_name', models.CharField(max_length=32)),
                ('mobile', models.CharField(max_length=13)),
                ('pincode', models.CharField(max_length=10)),
                ('street_address', models.CharField(max_length=256)),
                ('landmark', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=32)),
                ('is_shipping', models.BooleanField()),
                ('is_billing', models.BooleanField()),
                ('is_default_shipping', models.BooleanField()),
                ('is_default_billing', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_addresses',
            },
        ),
    ]
